[package]
name = "worms_ai_loop"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
log = "0.4.27"
simple-logging = "2.0.2"
windows = { version = "0.61.3", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemServices",
] }
